pimcore:
    objects:
        class_definitions:
            data:
                prefixes:
                    - CoreShop\Bundle\RmaBundle\CoreExtension

jms_serializer:
    metadata:
        directories:
            coreshop-rma-component:
                namespace_prefix: 'CoreShop\Component\Rma'
                path: '@CoreShopRmaBundle/Resources/config/serializer'
