framework:
    workflows:
        coreshop_return:
            type: 'state_machine'
            marking_store:
                service: coreshop.state_machine.marking_store.return_pimcore_marking_store
            supports: CoreShop\Component\Rma\Model\OrderReturn

core_shop_workflow:
    state_machine:
        coreshop_return:
            places:
                - new
                - confirmed
                - cancelled
                - received
            transitions:
                create:
                    from: [new]
                    to: confirmed
                receive:
                    from: [confirmed]
                    to: received
                cancel:
                    from: [confirmed]
                    to: cancelled
            place_colors:
                new: '#61c2cb'
                confirmed: '#feb624'
                cancelled: '#f2583e'
                received: '#5b981a'
            transition_colors:
                create: '#feb624'
                receive: '#5b981a'
                cancel: '#f2583e'
            callbacks:
                after:
                    resolve_state:
                        on: ['receive']
                        do: ['@CoreShop\Bundle\RmaBundle\StateResolver\OrderReturnStateResolver', 'resolve']
                        args: ['object.getOrder()']
                    add_to_history:
                        on: ['receive', 'cancel']
                        do: ['@CoreShop\Bundle\WorkflowBundle\History\StateHistoryLoggerInterface', 'log']
                        args: ['object.getOrder()', 'event']
