parameters:
    coreshop_mcp.default_admin_username: 'admin'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CoreShop\Bundle\PimcoreMcpBundle\Tool\:
        resource: '../../Tool/'

    CoreShop\Bundle\PimcoreMcpBundle\Security\McpAccessTokenHandler:
        arguments:
            $apiToken: '%env(default::MCP_API_TOKEN)%'
            $adminUsername: '%env(default:coreshop_mcp.default_admin_username:MCP_ADMIN_USERNAME)%'
