services:
    coreshop.datahub.graphql.querytypegenerator.resource.product_store_price:
        class: CoreShop\Component\Resource\DataHub\QueryType\ResourceList
        arguments:
            - '@Pimcore\Bundle\DataHubBundle\GraphQL\Service'
            - '@coreshop.data_hub.doctrine_provider'
            - '%coreshop.model.product_store_price.class%'
        tags:
            - { name: pimcore.datahub.graphql.dataobjectquerytypegenerator, id: typegenerator_dataobjectquerydatatype_coreShopStorePrice }


    coreshop.datahub.graphql.querytypegenerator.resource.product_store_values:
        class: CoreShop\Component\Resource\DataHub\QueryType\ResourceList
        arguments:
            - '@Pimcore\Bundle\DataHubBundle\GraphQL\Service'
            - '@coreshop.data_hub.doctrine_provider'
            - '%coreshop.model.product_store_values.class%'
        tags:
            - { name: pimcore.datahub.graphql.dataobjectquerytypegenerator, id: typegenerator_dataobjectquerydatatype_coreShopStoreValues }

    CoreShop\Bundle\CoreBundle\DataHub\InputType\AddToCartInputItemTypeExtension:
        arguments:
            - '@CoreShop\Bundle\ResourceBundle\DataHub\InputTypeFactoryInterface'
        tags:
            - { name: coreshop.datahub.input_type_extension }

    CoreShop\Bundle\CoreBundle\DataHub\InputType\CartItemInputItemTypeExtension:
        tags:
            - { name: coreshop.datahub.input_type_extension }

    CoreShop\Bundle\CoreBundle\DataHub\Query\Extension\AddToCartMutationQueryExtension:
        tags:
            - { name: coreshop.datahub.query_extension }
