imports:
    - { resource: services/order_return.yml }
    - { resource: services/workflow.yml }
    - { resource: services/forms.yml }

services:
    _defaults:
        public: true

    coreshop.order.return.processable:
        class: CoreShop\Component\Order\Processable\ProcessableOrderItems
        arguments:
            - '@coreshop.repository.order_return'
            - !php/const CoreShop\Component\Rma\ReturnStates::STATE_CANCELLED
