services:
    _defaults:
        public: true

    CoreShop\Bundle\RmaBundle\StateResolver\OrderReturnStateResolver:
        public: true
        arguments:
            - '@CoreShop\Bundle\WorkflowBundle\Manager\StateMachineManagerInterface'
            - '@coreshop.repository.order_return'
            - '@coreshop.order.return.processable'

    coreshop.state_machine.marking_store.single_state.order_return_state:
        class: Symfony\Component\Workflow\MarkingStore\MethodMarkingStore
        arguments:
            - true
            - returnState

    coreshop.state_machine.marking_store.order_return_pimcore_marking_store:
        class: CoreShop\Bundle\WorkflowBundle\MarkingStore\PimcorePersistentMarkingStore
        arguments:
            - '@coreshop.state_machine.marking_store.single_state.order_return_state'

    coreshop.state_machine.marking_store.single_state.return_state:
        class: Symfony\Component\Workflow\MarkingStore\MethodMarkingStore
        arguments:
            - true
            - state

    coreshop.state_machine.marking_store.return_pimcore_marking_store:
        class: CoreShop\Bundle\WorkflowBundle\MarkingStore\PimcorePersistentMarkingStore
        arguments:
            - '@coreshop.state_machine.marking_store.single_state.return_state'
